// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/trip/v1/trip.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_api_proto_trip_v1_trip_proto_rawDescGZIP(), []int{0}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Trip) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Trip) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trip) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	StartLat      float64                `protobuf:"fixed64,2,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLon      float64                `protobuf:"fixed64,3,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	EndLat        float64                `protobuf:"fixed64,4,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLon        float64                `protobuf:"fixed64,5,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trip_v1_trip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateTripRequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *CreateTripRequest) GetStartLon() float64 {
	if x != nil {
		return x.StartLon
	}
	return 0
}

func (x *CreateTripRequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *CreateTripRequest) GetEndLon() float64 {
	if x != nil {
		return x.EndLon
	}
	return 0
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trip_v1_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trip_v1_trip_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

var File_api_proto_trip_v1_trip_proto protoreflect.FileDescriptor

const file_api_proto_trip_v1_trip_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/trip/v1/trip.proto\x12\atrip.v1\"|\n" +
	"\x04Trip\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\x9a\x01\n" +
	"\x11CreateTripRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1b\n" +
	"\tstart_lat\x18\x02 \x01(\x01R\bstartLat\x12\x1b\n" +
	"\tstart_lon\x18\x03 \x01(\x01R\bstartLon\x12\x17\n" +
	"\aend_lat\x18\x04 \x01(\x01R\x06endLat\x12\x17\n" +
	"\aend_lon\x18\x05 \x01(\x01R\x06endLon\"7\n" +
	"\x12CreateTripResponse\x12!\n" +
	"\x04trip\x18\x01 \x01(\v2\r.trip.v1.TripR\x04trip2T\n" +
	"\vTripService\x12E\n" +
	"\n" +
	"CreateTrip\x12\x1a.trip.v1.CreateTripRequest\x1a\x1b.trip.v1.CreateTripResponseB\x18Z\x16uber-clone/pkg/trip/v1b\x06proto3"

var (
	file_api_proto_trip_v1_trip_proto_rawDescOnce sync.Once
	file_api_proto_trip_v1_trip_proto_rawDescData []byte
)

func file_api_proto_trip_v1_trip_proto_rawDescGZIP() []byte {
	file_api_proto_trip_v1_trip_proto_rawDescOnce.Do(func() {
		file_api_proto_trip_v1_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_trip_v1_trip_proto_rawDesc), len(file_api_proto_trip_v1_trip_proto_rawDesc)))
	})
	return file_api_proto_trip_v1_trip_proto_rawDescData
}

var file_api_proto_trip_v1_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_trip_v1_trip_proto_goTypes = []any{
	(*Trip)(nil),               // 0: trip.v1.Trip
	(*CreateTripRequest)(nil),  // 1: trip.v1.CreateTripRequest
	(*CreateTripResponse)(nil), // 2: trip.v1.CreateTripResponse
}
var file_api_proto_trip_v1_trip_proto_depIdxs = []int32{
	0, // 0: trip.v1.CreateTripResponse.trip:type_name -> trip.v1.Trip
	1, // 1: trip.v1.TripService.CreateTrip:input_type -> trip.v1.CreateTripRequest
	2, // 2: trip.v1.TripService.CreateTrip:output_type -> trip.v1.CreateTripResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_trip_v1_trip_proto_init() }
func file_api_proto_trip_v1_trip_proto_init() {
	if File_api_proto_trip_v1_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_trip_v1_trip_proto_rawDesc), len(file_api_proto_trip_v1_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_trip_v1_trip_proto_goTypes,
		DependencyIndexes: file_api_proto_trip_v1_trip_proto_depIdxs,
		MessageInfos:      file_api_proto_trip_v1_trip_proto_msgTypes,
	}.Build()
	File_api_proto_trip_v1_trip_proto = out.File
	file_api_proto_trip_v1_trip_proto_goTypes = nil
	file_api_proto_trip_v1_trip_proto_depIdxs = nil
}
