// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateWithGoogleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateWithGoogleRequest) Reset() {
	*x = AuthenticateWithGoogleRequest{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateWithGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateWithGoogleRequest) ProtoMessage() {}

func (x *AuthenticateWithGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateWithGoogleRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateWithGoogleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateWithGoogleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthenticateWithGoogleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateWithGoogleResponse) Reset() {
	*x = AuthenticateWithGoogleResponse{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateWithGoogleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateWithGoogleResponse) ProtoMessage() {}

func (x *AuthenticateWithGoogleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateWithGoogleResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateWithGoogleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateWithGoogleResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Or more user details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/auth/v1/auth.proto\x12\aauth.v1\"3\n" +
	"\x1dAuthenticateWithGoogleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"6\n" +
	"\x1eAuthenticateWithGoogleResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\".\n" +
	"\x13VerifyTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xc2\x01\n" +
	"\vAuthService\x12i\n" +
	"\x16AuthenticateWithGoogle\x12&.auth.v1.AuthenticateWithGoogleRequest\x1a'.auth.v1.AuthenticateWithGoogleResponse\x12H\n" +
	"\vVerifyToken\x12\x1b.auth.v1.VerifyTokenRequest\x1a\x1c.auth.v1.VerifyTokenResponseB1Z/github.com/lukabrx/uber-clone/api/proto/auth/v1b\x06proto3"

var (
	file_api_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_api_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_v1_auth_proto_rawDesc), len(file_api_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_v1_auth_proto_rawDescData
}

var file_api_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_auth_v1_auth_proto_goTypes = []any{
	(*AuthenticateWithGoogleRequest)(nil),  // 0: auth.v1.AuthenticateWithGoogleRequest
	(*AuthenticateWithGoogleResponse)(nil), // 1: auth.v1.AuthenticateWithGoogleResponse
	(*VerifyTokenRequest)(nil),             // 2: auth.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),            // 3: auth.v1.VerifyTokenResponse
}
var file_api_proto_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.AuthenticateWithGoogle:input_type -> auth.v1.AuthenticateWithGoogleRequest
	2, // 1: auth.v1.AuthService.VerifyToken:input_type -> auth.v1.VerifyTokenRequest
	1, // 2: auth.v1.AuthService.AuthenticateWithGoogle:output_type -> auth.v1.AuthenticateWithGoogleResponse
	3, // 3: auth.v1.AuthService.VerifyToken:output_type -> auth.v1.VerifyTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_auth_v1_auth_proto_init() }
func file_api_proto_auth_v1_auth_proto_init() {
	if File_api_proto_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_v1_auth_proto_rawDesc), len(file_api_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_v1_auth_proto = out.File
	file_api_proto_auth_v1_auth_proto_goTypes = nil
	file_api_proto_auth_v1_auth_proto_depIdxs = nil
}
